### Question 1

What's the version of NumPy that you installed? 

You can get the version information using the `__version__` field:


In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.3'

### Getting the data 

For this homework, we'll use the Car price dataset. Download it from 
[here](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv).

You can do it with wget:

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-18 14:04:16--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1,41M  2,56MB/s    in 0,5s    

2022-09-18 14:04:17 (2,56 MB/s) - ‘data.csv’ saved [1475504/1475504]



### Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

- 16
- 6572
- **11914**
- 18990

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')

In [5]:
df.shape

(11914, 16)

### Question 3

Who are the most frequent car manufacturers (top-3) according to the dataset?

- Chevrolet, Volkswagen, Toyota
- Chevrolet, Ford, Toyota
- Ford, Volkswagen, Toyota
- **Chevrolet, Ford, Volkswagen**

> **Note**: You should rely on "Make" column in this question.


In [6]:
df['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4

What's the number of unique Audi car models in the dataset?

- 3
- 16
- 26
- **34**

In [7]:
df.loc[df['Make'] == 'Audi', 'Model'].nunique()

34

### Question 5

How many columns in the dataset have missing values?

- **5**
- 6
- 7
- 8

In [8]:
df.isna().any(axis=0).sum()

5

### Question 6

1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

> Hint: refer to existing `mode` and `median` functions to complete the task.

- Yes
- **No**

In [9]:
df['Engine Cylinders'].median()

6.0

In [10]:
df['Engine Cylinders'].mode().values[0]

4.0

In [11]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode().values[0])

In [12]:
df['Engine Cylinders'].median()

6.0

### Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Compute the inverse of `XTX`.
7. Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the value of the first element of `w`?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- -0.0723
- **4.5949**
- 31.6537
- 63.5643

In [13]:
mask = df['Make'] == 'Lotus'
clms = ['Engine HP', 'Engine Cylinders']
X = df.loc[mask, clms].drop_duplicates().values

In [14]:
XTX = X.T @ X

In [15]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [16]:
XTX_inv = np.linalg.inv(XTX)

In [17]:
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [18]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [19]:
w = (XTX_inv @ X.T) @ y

In [20]:
w

array([  4.59494481, -63.56432501])